version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports: 
      - '3000:3000'
    volumes:
      - '.:/paradigm_shift_docker'
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
    depends_on:
      - db


