version: "3.8"

services:
  db:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password     
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
  

  api:
    container_name: back-end
    build:
      context: ./back-end
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    environment:
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/paradigm_shift_docker
    depends_on:
      - db

  front:
    container_name: front-end
    build:
      context: ./front-end
      args:
        WORKDIR: app
        CONTAINER_PORT: 3000
        API_URL: "http://localhost:3000"
    stdin_open: true
    tty: true
    command: npm run dev
    volumes:
      - ./front-end:/app
    ports:
      - "8080:8080"
    depends_on:
      - api



