version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  heroku: circleci/heroku@1.2.3
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.0.0
  

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: paradigm_shift_ver1_6_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/paradigm_shift_ver1.6/back-end
    steps:
      - checkout:
          path: ~/paradigm_shift_ver1.6
      - run: sudo apt-get update
      - run: sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
      - run: sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev
      - ruby/install-deps
      - run:
          name: Database setup1
          command: bundle exec rails db:migrate
      - run:
          name: Database setup2
          command: bundle exec rails db:seed
      - run:
          name: test
          command: bundle exec rake spec

workflows:
    build_and_test_and_deploy_backend:
          jobs:
          - build_and_test 
          - aws-ecr/build-and-push-image:
              requires:
                  - build_and_test 
              region: AWS_REGION
              account-url: AWS_ECR_ACCOUNT_URL
              repo: 'spa-back-paradigm-shift-ecr-terraform'
              path: ./back-end/
              dockerfile: Dockerfile
              extra-build-args: '--build-arg RAILS_PRODUCTION_KEY=${RAILS_PRODUCTION_KEY} --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --build-arg AWS_ACCESS_KEY_ID_CARRIER=${AWS_ACCESS_KEY_ID_CARRIER} --build-arg AWS_SECRET_ACCESS_KEY_CARRIER=${AWS_SECRET_ACCESS_KEY_CARRIER}'
              tag: '${CIRCLE_SHA1}'
         
              
          - aws-ecs/deploy-service-update:
              requires:
                  - aws-ecr/build-and-push-image
              family: 'spa-paradigm-shift-ecs-back-task-definition-terraform' # タスク名
              cluster-name: 'spa-paradigm-shift-ecs-cluster-terraform'
              service-name: 'spa-back-paradigm-shift-ecs-servic-terraform'
              container-image-name-updates: 'container=spa-paradigm-shift-ecs-back-container-terraform,tag=${CIRCLE_SHA1}'
       

    build_and_deploy_frontend:
          jobs: 
          - aws-ecr/build-and-push-image:
              region: AWS_REGION
              account-url: AWS_ECR_ACCOUNT_URL
              repo: 'spa-front-paradigm-shift-ecr-terraform'
              path: ./front-end/
              dockerfile: Dockerfile
              tag: '${CIRCLE_SHA1}'
              filters:    
                branches:
                    only:
                    - main
          
       
          - aws-ecs/deploy-service-update:
              requires:
                  - aws-ecr/build-and-push-image
              family: 'spa-paradigm-shift-ecs-front-task-definition-terraform' # タスク名
              cluster-name: 'spa-paradigm-shift-ecs-cluster-terraform'
              service-name: 'spa-front-paradigm-shift-ecs-servic-terraform'
              container-image-name-updates: 'container=spa-paradigm-shift-ecs-front-container-terraform,tag=${CIRCLE_SHA1}'
              filters:    
                branches:
                    only:
                    - main  