version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  heroku: circleci/heroku@1.2.3
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.0.0
  

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: paradigm_shift_ver1_6_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/paradigm_shift_ver1.6/back-end
    steps:
      - checkout:
          path: ~/paradigm_shift_ver1.6
      - run: sudo apt-get update
      - run: sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
      - run: sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev
      - ruby/install-deps
      - run:
          name: Database setup1
          command: bundle exec rails db:create
      - run:
          name: Database setup2
          command: bundle exec rails db:migrate
      - run:
          name: Database setup3
          command: bundle exec rails db:seed
      - run:
          name: test
          command: bundle exec rake spec

workflows:
    build_and_test:
          jobs:
          - build_and_test 
          
              

         