
version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  heroku: circleci/heroku@1.2.3
  

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: paradigm_shift_ver1_6_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/paradigm_shift_ver1.6
    steps:
      - checkout:
          path: ~/paradigm_shift_ver1.6
      - run: sudo apt-get update
      - run: sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
      - run: sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev
      - ruby/install-deps
      - run:
          name: Database setup1
          command: bundle exec rails db:migrate
      - run:
          name: Database setup2
          command: bundle exec rails db:seed
      - run:
          name: test
          command: bundle exec rake spec

  deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run: sudo apt-get update
      - run: sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
      - run: sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev
      - ruby/install-deps
      - add_ssh_keys:
          fingerprints: "15:f2:e0:83:58:75:2e:ec:4f:ff:61:15:8e:3b:cb:96"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy



workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
              branches:
                only: main
      
