
version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  heroku: circleci/heroku@1.2.3
  

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: paradigm_shift_ver1_6_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/paradigm_shift_ver1.6
    steps:
      - checkout:
          path: ~/paradigm_shift_ver1.6
      - add_ssh_keys:
          fingerprints: "9a:60:9f:39:4d:3b:c0:c1:6d:a4:01:54:05:b1:cd:b1"
      - run: sudo apt-get update
      - run: sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
      - run: sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev
      - ruby/install-deps
      - run:
          name: Database setup1
          command: bundle exec rails db:migrate
      - run:
          name: Database setup2
          command: bundle exec rails db:seed
      - run:
          name: test
          command: bundle exec rake spec

  deploy:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME
      - run:
          name: database setup2
          command: heroku run bundle exec rake db:seed RAILS_ENV=production -a $HEROKU_APP_NAME


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
               only: main
      
