
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/paradigm_shift_ver1.6
    steps:
      - checkout:
          path: ~/paradigm_shift_ver1.6
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: paradigm_shift_ver1_6_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/paradigm_shift_ver1.6
    steps:
      - checkout:
          path: ~/paradigm_shift_ver1.6
      - ruby/install-deps
      - run:
          name: Database setup1
          command: bundle exec rails db:migrate
      - run:
          name: Database setup2
          command: bundle exec rails db:seed
      - run:
          name: test
          command: bundle exec rake spec

 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      